FROM ubuntu:16.04

LABEL maintainer="Suxing Liu, Wes Bonelli"

RUN mkdir -p /opt/code
COPY / /opt/code

RUN apt-get update && \
    apt-get install -y tzdata 
    
RUN apt-get install -y \
    wget \
    build-essential \
    python3-setuptools \
    python3-pip \
    python3 \
    unzip \
    glew-utils \
    imagemagick \
    libgtk2.0-dev \
    libglew-dev \
    libdevil-dev \
    libboost-all-dev \
    libatlas-cpp-0.6-dev \
    libatlas-base-dev \
    liblapack3 \
    libblas3 \
    libblas-dev \
    libcminpack-dev \
    libgfortran5 \
    libmetis-edf-dev \
    libparmetis-dev \
    libjpeg-turbo8 \
    libgsl-dev \
    freeglut3-dev

RUN cd /opt/code && \
    make clean && \
    make all && \
    mkdir /lscratch /db /work /scratch && \
    chmod -R a+rwx /opt/code

RUN pip3 install --upgrade pip && \
    pip3 install -r /opt/code/requirements.txt

ENV PATH=$PATH:/opt/code/vsfm/bin/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/code/vsfm/bin/
ENV QT_QPA_PLATFORM=offscreen

RUN mkdir -p /opt/code/vsfm/bin/log && \
    mkdir -p /opt/code/vsfm/bin/temp/log && \
    touch /opt/code/vsfm/bin/temp/temp.pgm && \
    touch /opt/code/vsfm/bin/temp/temp.sift.sift && \
    ln -s /opt/code/vsfm/bin/temp/temp.pgm /opt/code/vsfm/bin/temp.pgm && \
    ln -s /opt/code/vsfm/bin/temp/temp.sift.sift /opt/code/vsfm/bin/temp.sift.sift && \
    ln -s /opt/code/vsfm/bin/temp/log /opt/code/vsfm/bin/log

