FROM geki/colmap
LABEL maintainer="Suxing Liu, Wes Bonelli"
COPY . /opt/code
WORKDIR /opt/code


RUN apt -y update 



RUN apt-get -ym update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    wget \
    cmake \
    tzdata \
    build-essential \
    mlocate \
    python3-pip \
    python3 \
    python3-setuptools \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-graph-dev \
    libboost-regex-dev \
    libboost-system-dev \
    libboost-test-dev \
    libeigen3-dev \
    libsuitesparse-dev \
    libfreeimage-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libglfw3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    freeglut3-dev \
    libglew-dev \
    libdevil-dev \
    qtbase5-dev \
    libqt5opengl5-dev \
    libcgal-dev \
    unzip 


RUN mkdir /lscratch /db /work /scratch && \
    chmod -R a+rwx /opt/code


RUN strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so


RUN pip3 install --upgrade pip && \
    pip3 install -r /opt/code/requirements.txt


ENV QT_QPA_PLATFORM=offscreen
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
